// Generated by data binding compiler. Do not edit!
package com.incampusit.staryaar.argear;

import android.annotation.SuppressLint;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.ToggleButton;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.databinding.DataBindingUtil;
import androidx.databinding.ViewDataBinding;

import com.incampusit.staryaar.R;

public abstract class ActivityCameraBinding extends ViewDataBinding {
    @NonNull
    public final Button beautyButton;

    @NonNull
    public final View bottomRatioView;

    @NonNull
    public final Button bulgeButton;

    @NonNull
    public final FrameLayout cameraLayout;

    @NonNull
    public final Button cameraSwitchButton;

    @NonNull
    public final Button filterButton;

    @NonNull
    public final LinearLayout functionsLayout;

    @NonNull
    public final Button moreButton;

    @NonNull
    public final LayoutMoreBinding moreLayout;

    @NonNull
    public final ProgressBar progressBar;

    @NonNull
    public final ToggleButton shutterButton;

    @NonNull
    public final LinearLayout shutterLayout;

    @NonNull
    public final UnderLineView shutterPhotoButton;

    @NonNull
    public final UnderLineView shutterVideoButton;

    @NonNull
    public final FrameLayout slotContainer;

    @NonNull
    public final Button stickerButton;

    @NonNull
    public final View topRatioView;

    protected ActivityCameraBinding(Object _bindingComponent, View _root, int _localFieldCount,
                                    Button beautyButton, View bottomRatioView, Button bulgeButton, FrameLayout cameraLayout,
                                    Button cameraSwitchButton, Button filterButton, LinearLayout functionsLayout,
                                    Button moreButton, LayoutMoreBinding moreLayout, ProgressBar progressBar,
                                    ToggleButton shutterButton, LinearLayout shutterLayout, UnderLineView shutterPhotoButton,
                                    UnderLineView shutterVideoButton, FrameLayout slotContainer, Button stickerButton,
                                    View topRatioView) {
        super(_bindingComponent, _root, _localFieldCount);
        this.beautyButton = beautyButton;
        this.bottomRatioView = bottomRatioView;
        this.bulgeButton = bulgeButton;
        this.cameraLayout = cameraLayout;
        this.cameraSwitchButton = cameraSwitchButton;
        this.filterButton = filterButton;
        this.functionsLayout = functionsLayout;
        this.moreButton = moreButton;
        this.moreLayout = moreLayout;
        setContainedBinding(this.moreLayout);
        this.progressBar = progressBar;
        this.shutterButton = shutterButton;
        this.shutterLayout = shutterLayout;
        this.shutterPhotoButton = shutterPhotoButton;
        this.shutterVideoButton = shutterVideoButton;
        this.slotContainer = slotContainer;
        this.stickerButton = stickerButton;
        this.topRatioView = topRatioView;
    }

    @NonNull
    public static ActivityCameraBinding inflate(@NonNull LayoutInflater inflater,
                                                @Nullable ViewGroup root, boolean attachToRoot) {
        return inflate(inflater, root, attachToRoot, DataBindingUtil.getDefaultComponent());
    }

    /**
     * This method receives DataBindingComponent instance as type Object instead of
     * type DataBindingComponent to avoid causing too many compilation errors if
     * compilation fails for another reason.
     * https://issuetracker.google.com/issues/116541301
     *
     * @Deprecated Use DataBindingUtil.inflate(inflater, R.layout.activity_camera, root, attachToRoot, component)
     */
    @SuppressLint("RestrictedApi")
    @NonNull
    @Deprecated
    public static ActivityCameraBinding inflate(@NonNull LayoutInflater inflater,
                                                @Nullable ViewGroup root, boolean attachToRoot, @Nullable Object component) {
        return ViewDataBinding.inflateInternal(inflater, R.layout.activity_camera, root, attachToRoot, component);
    }

    @NonNull
    public static ActivityCameraBinding inflate(@NonNull LayoutInflater inflater) {
        return inflate(inflater, DataBindingUtil.getDefaultComponent());
    }

    /**
     * This method receives DataBindingComponent instance as type Object instead of
     * type DataBindingComponent to avoid causing too many compilation errors if
     * compilation fails for another reason.
     * https://issuetracker.google.com/issues/116541301
     *
     * @Deprecated Use DataBindingUtil.inflate(inflater, R.layout.activity_camera, null, false, component)
     */
    @SuppressLint("RestrictedApi")
    @NonNull
    @Deprecated
    public static ActivityCameraBinding inflate(@NonNull LayoutInflater inflater,
                                                @Nullable Object component) {
        return ViewDataBinding.inflateInternal(inflater, R.layout.activity_camera, null, false, component);
    }

    public static ActivityCameraBinding bind(@NonNull View view) {
        return bind(view, DataBindingUtil.getDefaultComponent());
    }

    /**
     * This method receives DataBindingComponent instance as type Object instead of
     * type DataBindingComponent to avoid causing too many compilation errors if
     * compilation fails for another reason.
     * https://issuetracker.google.com/issues/116541301
     *
     * @Deprecated Use DataBindingUtil.bind(view, component)
     */
    @Deprecated
    public static ActivityCameraBinding bind(@NonNull View view, @Nullable Object component) {
        return (ActivityCameraBinding) bind(component, view, R.layout.activity_camera);
    }
}
