// Generated by data binding compiler. Do not edit!
package com.incampusit.staryaar.argear;

import android.annotation.SuppressLint;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.RadioButton;
import android.widget.RadioGroup;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.databinding.DataBindingUtil;
import androidx.databinding.ViewDataBinding;

import com.incampusit.staryaar.R;

public abstract class LayoutMoreBinding extends ViewDataBinding {
    @NonNull
    public final RadioGroup cameraRatioRadiogroup;

    @NonNull
    public final CheckBox debugLandmarkCheckbox;

    @NonNull
    public final CheckBox debugRectCheckbox;

    @NonNull
    public final RadioButton ratio11Radiobutton;

    @NonNull
    public final RadioButton ratio43Radiobugtton;

    @NonNull
    public final RadioButton ratioFullRadiobutton;

    protected LayoutMoreBinding(Object _bindingComponent, View _root, int _localFieldCount,
                                RadioGroup cameraRatioRadiogroup, CheckBox debugLandmarkCheckbox, CheckBox debugRectCheckbox,
                                RadioButton ratio11Radiobutton, RadioButton ratio43Radiobugtton,
                                RadioButton ratioFullRadiobutton) {
        super(_bindingComponent, _root, _localFieldCount);
        this.cameraRatioRadiogroup = cameraRatioRadiogroup;
        this.debugLandmarkCheckbox = debugLandmarkCheckbox;
        this.debugRectCheckbox = debugRectCheckbox;
        this.ratio11Radiobutton = ratio11Radiobutton;
        this.ratio43Radiobugtton = ratio43Radiobugtton;
        this.ratioFullRadiobutton = ratioFullRadiobutton;
    }

    @NonNull
    public static LayoutMoreBinding inflate(@NonNull LayoutInflater inflater,
                                            @Nullable ViewGroup root, boolean attachToRoot) {
        return inflate(inflater, root, attachToRoot, DataBindingUtil.getDefaultComponent());
    }

    /**
     * This method receives DataBindingComponent instance as type Object instead of
     * type DataBindingComponent to avoid causing too many compilation errors if
     * compilation fails for another reason.
     * https://issuetracker.google.com/issues/116541301
     *
     * @Deprecated Use DataBindingUtil.inflate(inflater, R.layout.layout_more, root, attachToRoot, component)
     */
    @SuppressLint("RestrictedApi")
    @NonNull
    @Deprecated
    public static LayoutMoreBinding inflate(@NonNull LayoutInflater inflater,
                                            @Nullable ViewGroup root, boolean attachToRoot, @Nullable Object component) {
        return ViewDataBinding.inflateInternal(inflater, R.layout.layout_more, root, attachToRoot, component);
    }

    @NonNull
    public static LayoutMoreBinding inflate(@NonNull LayoutInflater inflater) {
        return inflate(inflater, DataBindingUtil.getDefaultComponent());
    }

    /**
     * This method receives DataBindingComponent instance as type Object instead of
     * type DataBindingComponent to avoid causing too many compilation errors if
     * compilation fails for another reason.
     * https://issuetracker.google.com/issues/116541301
     *
     * @Deprecated Use DataBindingUtil.inflate(inflater, R.layout.layout_more, null, false, component)
     */
    @SuppressLint("RestrictedApi")
    @NonNull
    @Deprecated
    public static LayoutMoreBinding inflate(@NonNull LayoutInflater inflater,
                                            @Nullable Object component) {
        return ViewDataBinding.inflateInternal(inflater, R.layout.layout_more, null, false, component);
    }

    public static LayoutMoreBinding bind(@NonNull View view) {
        return bind(view, DataBindingUtil.getDefaultComponent());
    }

    /**
     * This method receives DataBindingComponent instance as type Object instead of
     * type DataBindingComponent to avoid causing too many compilation errors if
     * compilation fails for another reason.
     * https://issuetracker.google.com/issues/116541301
     *
     * @Deprecated Use DataBindingUtil.bind(view, component)
     */
    @Deprecated
    public static LayoutMoreBinding bind(@NonNull View view, @Nullable Object component) {
        return (LayoutMoreBinding) bind(component, view, R.layout.layout_more);
    }
}
